mode: "demo"
camera:
  f: 4.143903289
  sx: 4.968
  sy: 3.726
sun:
  energy_min: 10.0
  energy_max: 10.0
  local_time_min: 10.0
  local_time_max: 16.0
output:
  dir: output
  resolution_x: 640
  resolution_y: 480
  format: JPEG
  render: CYCLES
paths:
  number_of_samples: 200
  x_min: 0.0
  x_max: 800.0
  y_min: 0.0
  y_max: 7000.0
  z_min: 1.0
  z_max: 51.0
  euler_x_min: -0.3926991
  euler_x_max: 0.3926991
  euler_y_min: -0.3926991
  euler_y_max: 0.3926991
  euler_z_min: -3.141
  euler_z_max: 3.141
  seed: 1
  demo_x: 330.0
  demo_y: 3500.0
  demo_z: 30.0
  demo_radius: 50.0
