mode: "demo"
camera:
  f: 3.5
  sx: 4.96
  sy: 3.72
sun:
  energy_min: 10.0
  energy_max: 10.0
  local_time_min: 10.0
  local_time_max: 16.0
output:
  dir: output
  resolution_x: 640
  resolution_y: 480
  format: JPEG
  render: CYCLES
  use_second_view: False
paths:
  number_of_samples: 100
  x_min: 0.0
  x_max: 200.0
  y_min: 0.0
  y_max: 150.0
  z_min: 1.0
  z_max: 51.0
  euler_x_min: -0.1745
  euler_x_max: 0.1745
  euler_y_min: -0.1745
  euler_y_max: 0.1745
  euler_z_min: -3.141
  euler_z_max: 3.141
  seed: 1
  demo_x: 100.0
  demo_y: 75.0
  demo_z: 50.0
  demo_radius: 50.0
