mode: "demo"
camera:
  f: 2.8
  sx: 5.76
  sy: 3.6
sun:
  energy_min: 10.0
  energy_max: 10.0
  local_time_min: 10.0
  local_time_max: 16.0
output:
  dir: output
  resolution_x: 1920
  resolution_y: 1200
  format: JPEG
  render: CYCLES
  use_second_view: True
paths:
  number_of_samples: 100
  x_min: 0.0
  x_max: 200.0
  y_min: 0.0
  y_max: 150.0
  z_min: 1.0
  z_max: 51.0
  demo_euler_y: -0.785398
  seed: 1
  demo_x: 100.0
  demo_y: 75.0
  demo_z: 25.0
  demo_radius: 50.0
